// loading 
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'

//fetch user success

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

//FAILURE
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'